export const GAMES = [
  // ─── 1. HAFIZA (MEMORY) ────────────────────────────────────────────────────
  {
    id: 'memory-matrix',
    name: 'Hafıza Izgarası',
    category: 'memory',
    categoryLabel: 'Hafıza',
    difficulty: 2,
    icon: '⬛',
    description: 'Kare desenini hafızanda tut ve kutuları doğru hatırla.',
    timeLimit: 90,
    color: '#7c3aed',
    route: '/game/memory-matrix'
  },
  {
    id: 'letter-count',
    name: 'Harf Sayma',
    category: 'memory',
    categoryLabel: 'Hafıza',
    difficulty: 1,
    icon: '🔤',
    description: 'Gösterilen kelimelerdeki belirli harfleri say.',
    timeLimit: 60,
    color: '#7c3aed',
    route: '/game/letter-count'
  },
  {
    id: 'color-match',
    name: 'Renk Eşleştirme',
    category: 'memory',
    categoryLabel: 'Hafıza',
    difficulty: 1,
    icon: '🎨',
    description: 'Renkleri hafızanda tut ve eşleştir.',
    timeLimit: 60,
    color: '#7c3aed',
    route: '/game/color-match'
  },
  {
    id: 'number-sequence',
    name: 'Sayı Dizisi',
    category: 'memory',
    categoryLabel: 'Hafıza',
    difficulty: 2,
    icon: '🔢',
    description: 'Sayı dizisini ezberle ve tekrarla.',
    timeLimit: 90,
    color: '#7c3aed',
    route: '/game/number-sequence'
  },
  {
    id: 'card-flip',
    name: 'Kart Çevirme',
    category: 'memory',
    categoryLabel: 'Hafıza',
    difficulty: 2,
    icon: '🃏',
    description: 'Kartların yerlerini ezberle ve çiftleri bul.',
    timeLimit: 120,
    color: '#7c3aed',
    route: '/game/card-flip'
  },
  {
    id: 'word-memory',
    name: 'Kelime Ezber',
    category: 'memory',
    categoryLabel: 'Hafıza',
    difficulty: 2,
    icon: '📝',
    description: 'Kelime listesini kısa sürede ezberle.',
    timeLimit: 90,
    color: '#7c3aed',
    route: '/game/word-memory'
  },
  {
    id: 'image-memory',
    name: 'Görsel Hafıza',
    category: 'memory',
    categoryLabel: 'Hafıza',
    difficulty: 3,
    icon: '🖼️',
    description: 'Görsellerin konumlarını hatırla.',
    timeLimit: 120,
    color: '#7c3aed',
    route: '/game/image-memory'
  },
  {
    id: 'spatial-memory',
    name: 'Uzamsal Hafıza',
    category: 'memory',
    categoryLabel: 'Hafıza',
    difficulty: 2,
    icon: '🧭',
    description: '3D blokların konumunu ve hareket sırasını hatırla.',
    timeLimit: 90,
    color: '#7c3aed',
    route: '/game/spatial-memory'
  },
  {
    id: 'sound-memory',
    name: 'Melodi Hafızası',
    category: 'memory',
    categoryLabel: 'Hafıza',
    difficulty: 2,
    icon: '🎵',
    description: 'Çalınan nota ve ses dizilimini doğru sırala.',
    timeLimit: 60,
    color: '#7c3aed',
    route: '/game/sound-memory'
  },

  // ─── 2. HIZ (SPEED) ────────────────────────────────────────────────────────
  {
    id: 'snake-brain',
    name: 'Yılan',
    category: 'speed',
    categoryLabel: 'Hız',
    difficulty: 2,
    icon: '🐍',
    description: 'Yılanı yönet, elmayı ye, duvarlara çarpma!',
    timeLimit: 60,
    color: '#f59e0b',
    route: '/game/snake-brain'
  },
  {
    id: 'reaction-test',
    name: 'Tepki Testi',
    category: 'speed',
    categoryLabel: 'Hız',
    difficulty: 1,
    icon: '⚡',
    description: 'Uyarıya olabildiğince hızlı tepki ver.',
    timeLimit: 30,
    color: '#f59e0b',
    route: '/game/reaction-test'
  },
  {
    id: 'fast-math',
    name: 'Hızlı Matematik',
    category: 'speed',
    categoryLabel: 'Hız',
    difficulty: 2,
    icon: '➗',
    description: 'Matematik işlemlerini hızla çöz.',
    timeLimit: 60,
    color: '#f59e0b',
    route: '/game/fast-math'
  },
  {
    id: 'color-name-test',
    name: 'Renk Adı Testi',
    category: 'speed',
    categoryLabel: 'Hız',
    difficulty: 2,
    icon: '🌈',
    description: 'Renk adı ile renk rengini hızla karşılaştır.',
    timeLimit: 60,
    color: '#f59e0b',
    route: '/game/color-name-test'
  },
  {
    id: 'fast-sort',
    name: 'Hızlı Sıralama',
    category: 'speed',
    categoryLabel: 'Hız',
    difficulty: 3,
    icon: '📊',
    description: 'Sayıları hızla sırala.',
    timeLimit: 45,
    color: '#f59e0b',
    route: '/game/fast-sort'
  },
  {
    id: 'speed-type',
    name: 'Hızlı Yazım',
    category: 'speed',
    categoryLabel: 'Hız',
    difficulty: 3,
    icon: '⌨️',
    description: 'Gösterilen metni hızla yaz.',
    timeLimit: 60,
    color: '#f59e0b',
    route: '/game/speed-type'
  },
  {
    id: 'quick-click',
    name: 'Refleks Tıklama',
    category: 'speed',
    categoryLabel: 'Hız',
    difficulty: 1,
    icon: '💥',
    description: 'Rastgele beliren hedeflere milisaniyeler içinde tıkla.',
    timeLimit: 30,
    color: '#f59e0b',
    route: '/game/quick-click'
  },
  {
    id: 'chase-speed',
    name: 'Ok Takibi',
    category: 'speed',
    categoryLabel: 'Hız',
    difficulty: 3,
    icon: '🏹',
    description: 'Göz kırpan okların yönüne göre anında tepki ver.',
    timeLimit: 45,
    color: '#f59e0b',
    route: '/game/chase-speed'
  },

  // ─── 3. DİKKAT (ATTENTION) ─────────────────────────────────────────────────
  {
    id: 'stroop-test',
    name: 'Stroop Testi',
    category: 'attention',
    categoryLabel: 'Dikkat',
    difficulty: 2,
    icon: '🧠',
    description: 'Rengi mi metni mi? Değişen kurala göre hızlıca ayırt et.',
    timeLimit: 60,
    color: '#06b6d4',
    route: '/game/stroop-test'
  },
  {
    id: 'object-track',
    name: 'Nesne Takibi',
    category: 'attention',
    categoryLabel: 'Dikkat',
    difficulty: 3,
    icon: '👁️',
    description: 'Bardakların altında kaybolan madeni parayı takip et.',
    timeLimit: 90,
    color: '#06b6d4',
    route: '/game/object-track'
  },
  {
    id: 'dual-task',
    name: 'Çift Görev',
    category: 'attention',
    categoryLabel: 'Dikkat',
    difficulty: 3,
    icon: '🔄',
    description: 'Aynı anda iki farklı görevi yerine getir.',
    timeLimit: 90,
    color: '#06b6d4',
    route: '/game/dual-task'
  },
  {
    id: 'shape-count',
    name: 'Şekil Sayma',
    category: 'attention',
    categoryLabel: 'Dikkat',
    difficulty: 2,
    icon: '🔺',
    description: 'Karmaşık şekil havuzunda hedef geometrik şekli say.',
    timeLimit: 60,
    color: '#06b6d4',
    route: '/game/shape-count'
  },
  {
    id: 'visual-search',
    name: 'Görsel Arama',
    category: 'attention',
    categoryLabel: 'Dikkat',
    difficulty: 2,
    icon: '🕵️',
    description: 'Büyük matriste gizlenmiş hedef karakteri bul.',
    timeLimit: 60,
    color: '#06b6d4',
    route: '/game/visual-search'
  },
  {
    id: 'focus-switch',
    name: 'Odak Değişimi',
    category: 'attention',
    categoryLabel: 'Dikkat',
    difficulty: 3,
    icon: '💡',
    description: 'İki farklı odak merkezi arasında kesintisiz geçiş yap.',
    timeLimit: 90,
    color: '#06b6d4',
    route: '/game/focus-switch'
  },

  // ─── 4. PROBLEM ÇÖZME (PROBLEM SOLVING) ────────────────────────────────────
  {
    id: 'sudoku-classic',
    name: 'Sudoku',
    category: 'problem-solving',
    categoryLabel: 'Problem Çözme',
    difficulty: 3,
    icon: '🧩',
    description: 'Klasik 9x9 Sudoku bulmacasında eksik sayıları tamamla.',
    timeLimit: 300,
    color: '#10b981',
    route: '/game/sudoku-classic'
  },
  {
    id: 'logic-puzzle',
    name: 'Mantık Bulmacası',
    category: 'problem-solving',
    categoryLabel: 'Problem Çözme',
    difficulty: 2,
    icon: '💡',
    description: 'Sözel ilişki ifadeleriyle mantık kurarak soruları çöz.',
    timeLimit: 120,
    color: '#10b981',
    route: '/game/logic-puzzle'
  },
  {
    id: 'number-pyramid',
    name: 'Sayı Piramidi',
    category: 'problem-solving',
    categoryLabel: 'Problem Çözme',
    difficulty: 2,
    icon: '🔺',
    description: 'Tabandan tavana sayıları toplayarak piramidin zirvesine ulaş.',
    timeLimit: 120,
    color: '#10b981',
    route: '/game/number-pyramid'
  },
  {
    id: 'anagram',
    name: 'Anagram',
    category: 'problem-solving',
    categoryLabel: 'Problem Çözme',
    difficulty: 2,
    icon: '🔀',
    description: 'Karışık harfleri düzenleyerek kelime bul.',
    timeLimit: 60,
    color: '#10b981',
    route: '/game/anagram'
  },
  {
    id: 'pattern-complete',
    name: 'Örüntü Tamamla',
    category: 'problem-solving',
    categoryLabel: 'Problem Çözme',
    difficulty: 3,
    icon: '⬛',
    description: 'Örüntüdeki eksik parçayı bul.',
    timeLimit: 90,
    color: '#10b981',
    route: '/game/pattern-complete'
  },
  {
    id: 'path-find',
    name: 'Renk Akışı',
    category: 'problem-solving',
    categoryLabel: 'Problem Çözme',
    difficulty: 3,
    icon: '🗺️',
    description: 'Eşleşen renkli noktaları yolları kesiştirmeden birleştir.',
    timeLimit: 150,
    color: '#10b981',
    route: '/game/path-find'
  },
  {
    id: 'math-pyramid',
    name: 'Matematik Bulmacası',
    category: 'problem-solving',
    categoryLabel: 'Problem Çözme',
    difficulty: 2,
    icon: '➕',
    description: 'Eksik matematik denklemlerini mantık yürüterek tamamla.',
    timeLimit: 90,
    color: '#10b981',
    route: '/game/math-pyramid'
  },
  {
    id: 'block-fit',
    name: 'Blok Yerleştirme',
    category: 'problem-solving',
    categoryLabel: 'Problem Çözme',
    difficulty: 3,
    icon: '🧱',
    description: 'Geometrik blokları boşluksuz şekilde alana sığdır.',
    timeLimit: 120,
    color: '#10b981',
    route: '/game/block-fit'
  },
  {
    id: 'river-crossing',
    name: 'Nehir Geçişi',
    category: 'problem-solving',
    categoryLabel: 'Problem Çözme',
    difficulty: 3,
    icon: '🚣',
    description: 'Mantık bulmacasında karakterleri güvenle karşıya geçir.',
    timeLimit: 120,
    color: '#10b981',
    route: '/game/river-crossing'
  },

  // ─── 5. DİL (LANGUAGE) ─────────────────────────────────────────────────────
  {
    id: 'wordle-game',
    name: 'Kelime Bulmaca',
    category: 'language',
    categoryLabel: 'Dil',
    difficulty: 2,
    icon: '🔤',
    description: '5 harfli gizli Türkçe kelimeyi 6 tahminde bul.',
    timeLimit: 120,
    color: '#ec4899',
    route: '/game/wordle-game'
  },
  {
    id: 'word-chain',
    name: 'Kelime Zinciri',
    category: 'language',
    categoryLabel: 'Dil',
    difficulty: 2,
    icon: '⛓️',
    description: 'Bir önceki kelimenin son harfiyle yeni kelime üret.',
    timeLimit: 60,
    color: '#ec4899',
    route: '/game/word-chain'
  },
  {
    id: 'word-produce',
    name: 'Kelime Üretme',
    category: 'language',
    categoryLabel: 'Dil',
    difficulty: 2,
    icon: '💬',
    description: 'Verilen harflerden en fazla kelime üret.',
    timeLimit: 90,
    color: '#ec4899',
    route: '/game/word-produce'
  },
  {
    id: 'idiom-complete',
    name: 'Deyim Tamamla',
    category: 'language',
    categoryLabel: 'Dil',
    difficulty: 3,
    icon: '📚',
    description: 'Eksik kısmı olan deyimi tamamla.',
    timeLimit: 60,
    color: '#ec4899',
    route: '/game/idiom-complete'
  },
  {
    id: 'vocab-builder',
    name: 'Kelime Hazinesi',
    category: 'language',
    categoryLabel: 'Dil',
    difficulty: 2,
    icon: '📖',
    description: 'Eş anlamlı ve zıt anlamlı kelimeleri zamanla eşleştir.',
    timeLimit: 60,
    color: '#ec4899',
    route: '/game/vocab-builder'
  },
  {
    id: 'spelling-bee',
    name: 'Harf Dizilimi',
    category: 'language',
    categoryLabel: 'Dil',
    difficulty: 2,
    icon: '🐝',
    description: 'Karışık harflerden en uzun Türkçe sözcüğü kur.',
    timeLimit: 60,
    color: '#ec4899',
    route: '/game/spelling-bee'
  },
  {
    id: 'rhyme-finder',
    name: 'Kafiye Bulucu',
    category: 'language',
    categoryLabel: 'Dil',
    difficulty: 2,
    icon: '🎙️',
    description: 'Verilen kelimeye kafiyeli uyan seçenekleri hızla bul.',
    timeLimit: 60,
    color: '#ec4899',
    route: '/game/rhyme-finder'
  },
  {
    id: 'missing-letter',
    name: 'Eksik Harf',
    category: 'language',
    categoryLabel: 'Dil',
    difficulty: 1,
    icon: '✏️',
    description: 'Kelimenin içindeki eksik harfleri tamamla.',
    timeLimit: 45,
    color: '#ec4899',
    route: '/game/missing-letter'
  },
  {
    id: 'word-search',
    name: 'Kelime Avı',
    category: 'language',
    categoryLabel: 'Dil',
    difficulty: 2,
    icon: '🔎',
    description: 'Harf tablosu içerisinde saklanmış kelimeleri bul.',
    timeLimit: 90,
    color: '#ec4899',
    route: '/game/word-search'
  },
  {
    id: 'sentence-order',
    name: 'Cümle Kurma',
    category: 'language',
    categoryLabel: 'Dil',
    difficulty: 3,
    icon: '📑',
    description: 'Karışık verilen kelimeleri anlamlı bir cümle halinde diz.',
    timeLimit: 90,
    color: '#ec4899',
    route: '/game/sentence-order'
  },

  // ─── 6. ESNEKLİK (FLEXIBILITY) ─────────────────────────────────────────────
  {
    id: 'color-flex',
    name: 'Bukalemun Zihni',
    category: 'flexibility',
    categoryLabel: 'Esneklik',
    difficulty: 2,
    icon: '🎭',
    description: 'Renk ve kelime çelişkisine zihnini anında adapte et.',
    timeLimit: 60,
    color: '#ef4444',
    route: '/game/color-flex'
  },
  {
    id: 'category-switch',
    name: 'Kural Avcısı',
    category: 'flexibility',
    categoryLabel: 'Esneklik',
    difficulty: 3,
    icon: '🔍',
    description: 'Gizli eşleşme kuralını keşfet ve yeni kurallara adapte ol.',
    timeLimit: 60,
    color: '#ef4444',
    route: '/game/category-switch'
  },
  {
    id: 'dual-rule',
    name: 'Çift Kural',
    category: 'flexibility',
    categoryLabel: 'Esneklik',
    difficulty: 3,
    icon: '⚖️',
    description: 'İki kuralı aynı anda değerlendirip doğru kadranta refleks göster.',
    timeLimit: 90,
    color: '#ef4444',
    route: '/game/dual-rule'
  },
  {
    id: 'rule-switch',
    name: 'Renk Kuralı',
    category: 'flexibility',
    categoryLabel: 'Esneklik',
    difficulty: 2,
    icon: '🔀',
    description: 'Değişen renk kuralları ve tuzak butonlara dikkat et.',
    timeLimit: 60,
    color: '#ef4444',
    route: '/game/rule-switch'
  },
  {
    id: 'shape-flex',
    name: 'Geometrik Geçiş',
    category: 'flexibility',
    categoryLabel: 'Esneklik',
    difficulty: 2,
    icon: '🔷',
    description: 'Boyut ve şekil kuralları arasında zihinsel geçiş yap.',
    timeLimit: 60,
    color: '#ef4444',
    route: '/game/shape-flex'
  },
  {
    id: 'direction-switch',
    name: 'Ters Oklar',
    category: 'flexibility',
    categoryLabel: 'Esneklik',
    difficulty: 2,
    icon: '🏹',
    description: 'Dikkat dağıtıcı okları görmezden gel, doğru yöne tepki ver.',
    timeLimit: 45,
    color: '#ef4444',
    route: '/game/direction-switch'
  },
  {
    id: 'multi-trait',
    name: 'Çoklu Özellik',
    category: 'flexibility',
    categoryLabel: 'Esneklik',
    difficulty: 3,
    icon: '🎨',
    description: 'Renk, şekil ve sayı boyutlarında çoklu analiz yap.',
    timeLimit: 60,
    color: '#ef4444',
    route: '/game/multi-trait'
  },
  {
    id: 'task-switch',
    name: 'Zihinsel Vites',
    category: 'flexibility',
    categoryLabel: 'Esneklik',
    difficulty: 3,
    icon: '🔄',
    description: 'Sayı ve harf modları arasında hızla geçiş yap.',
    timeLimit: 90,
    color: '#ef4444',
    route: '/game/task-switch'
  },
  {
    id: 'emotion-flex',
    name: 'Jest ve Renk',
    category: 'flexibility',
    categoryLabel: 'Esneklik',
    difficulty: 2,
    icon: '😀',
    description: 'Duygusal mimikler ve renklerle oluşan görsel tuzakları aş.',
    timeLimit: 60,
    color: '#ef4444',
    route: '/game/emotion-flex'
  },
  {
    id: 'number-letter-switch',
    name: 'Matris Refleksi',
    category: 'flexibility',
    categoryLabel: 'Esneklik',
    difficulty: 3,
    icon: '🔢',
    description: 'Sayısal ve sözel algı modları arasında milisaniyeler içinde geçiş yap.',
    timeLimit: 90,
    color: '#ef4444',
    route: '/game/number-letter-switch'
  }
];

export const CATEGORIES = [
  { id: 'all', label: 'Tüm Oyunlar', icon: '✨', color: '#3b82f6' },
  { id: 'memory', label: 'Hafıza', icon: '🧠', color: '#7c3aed' },
  { id: 'speed', label: 'Hız', icon: '⚡', color: '#f59e0b' },
  { id: 'attention', label: 'Dikkat', icon: '🎯', color: '#06b6d4' },
  { id: 'problem-solving', label: 'Problem Çözme', icon: '🧩', color: '#10b981' },
  { id: 'language', label: 'Dil', icon: '💬', color: '#ec4899' },
  { id: 'flexibility', label: 'Esneklik', icon: '🔄', color: '#ef4444' }
];
